#!/bin/sh
# autopkgtest check
# (C) 2018 Anton Gladky <gladk@debian.org>

set -e

export OMPI_MCA_orte_rsh_agent=/bin/false

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM

mkdir -p $WORKDIR/src
cp examples/interactions/* $WORKDIR/src/
cd $WORKDIR/src

cat <<EOF > CMakeLists.txt
project(plots CXX)
cmake_minimum_required(VERSION 3.7)

FIND_PACKAGE(QCustomPlot REQUIRED)
FIND_PACKAGE(Qt5PrintSupport REQUIRED)
set(CMAKE_MODULE_PATH "\${CMAKE_CURRENT_SOURCE_DIR}/cMake")

set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_AUTOUIC ON)


if(CMAKE_VERSION VERSION_LESS "3.7.0")
    set(CMAKE_INCLUDE_CURRENT_DIR ON)
endif()

INCLUDE(GNUInstallDirs)
find_package(Qt5 COMPONENTS Widgets REQUIRED)
INCLUDE_DIRECTORIES(\${CMAKE_CURRENT_BINARY_DIR} \${QCustomPlot_INCLUDE_DIR})

ADD_DEFINITIONS(-DQCUSTOMPLOT_USE_LIBRARY -fPIC)
INCLUDE_DIRECTORIES(\${Qt5Widgets_INCLUDE_DIRS})
ADD_EXECUTABLE(plots main.cpp mainwindow.cpp \${UI_HEADERS})

TARGET_LINK_LIBRARIES(plots Qt5::Widgets QCustomPlot::QCustomPlot)
INSTALL(TARGETS plots DESTINATION \${CMAKE_INSTALL_BINDIR})

EOF


cd ..
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=./../inst ./../src
make
make install
echo "build: OK"
# [ -x plots ]
# timeout 5 xvfb-run ./plots
# echo "run: OK"
ls -ln
